### ISSUE TITLE
Download is not syntactically correct turtle

### ISSUE THREAD

**Issue by larsgsvensson** [saidfathalla/EVENTSKG-Dataset#3]
**Describe the bug**
The [data download](https://github.com/saidfathalla/EVENTSKG-Dataset/blob/master/EVENTKG_R2.ttl?raw=true) is not syntactically correct. Parsing the data with `riot` throws errors. 

**To Reproduce**
1. Download the file: `wget https://github.com/saidfathalla/EVENTSKG-Dataset/blob/master/EVENTKG_R2.ttl?raw=true`
2. Rename to EVENTKG_R2.ttl: `mv EVENTKG_R2.ttl?raw=true EVENTKG_R2.ttl`
3. Execute `riot --validate EVENTKG_R2.ttl`
4. Parser says `ERROR riot                 :: [line: 849, col: 52] Triples not terminated by DOT`

**Expected behavior**
riot should not throw any errors.

I think there are more errors in the file. A visual inspection showed instances where the objects of `conference-ontology:endDate` were not in quotation marks.

**Comment by saidfathalla** [comment]
At this time, the turtle file was not ready. Now we have updated all serializations of the dataset and we validate the dataset using W3C RDF validator. I hope you do not get more errors :)
