### ISSUE TITLE
Entity ID does not conform to naming convention

### ISSUE THREAD

**Issue by larsgsvensson** [saidfathalla/EVENTSKG-Dataset#4]
**Describe the bug**
There is an entity http://purl.org/events_ds/CSC2017W in the dataset

**Expected behavior**
Since all other entities have IDs looking like `<name><year>` the expected ID should be http://purl.org/events_ds/CSC2017

**Comment by saidfathalla** [comment]
Thanks for your feedback. you are right. I fixed all these entries. In addition, the dataset URI has been changed to  http://purl.org/events_ds#
